# CMake generated Testfile for 
# Source directory: /home/mohamednadeem/project/htd/test/htd
# Build directory: /home/mohamednadeem/project/htd/test/htd
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BucketEliminationGraphDecompositionAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/BucketEliminationGraphDecompositionAlgorithmTest")
set_tests_properties(BucketEliminationGraphDecompositionAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(BucketEliminationTreeDecompositionAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/BucketEliminationTreeDecompositionAlgorithmTest")
set_tests_properties(BucketEliminationTreeDecompositionAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(ConnectedComponentAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/ConnectedComponentAlgorithmTest")
set_tests_properties(ConnectedComponentAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(FactoryTest "/home/mohamednadeem/project/htd/test/htd/FactoryTest")
set_tests_properties(FactoryTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(FilteredHyperedgeCollectionTest "/home/mohamednadeem/project/htd/test/htd/FilteredHyperedgeCollectionTest")
set_tests_properties(FilteredHyperedgeCollectionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(GraphDecompositionTest "/home/mohamednadeem/project/htd/test/htd/GraphDecompositionTest")
set_tests_properties(GraphDecompositionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(GraphLabelingTest "/home/mohamednadeem/project/htd/test/htd/GraphLabelingTest")
set_tests_properties(GraphLabelingTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(GraphPreprocessorTest "/home/mohamednadeem/project/htd/test/htd/GraphPreprocessorTest")
set_tests_properties(GraphPreprocessorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(GraphTest "/home/mohamednadeem/project/htd/test/htd/GraphTest")
set_tests_properties(GraphTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(HelperTest "/home/mohamednadeem/project/htd/test/htd/HelperTest")
set_tests_properties(HelperTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(HyperedgeTest "/home/mohamednadeem/project/htd/test/htd/HyperedgeTest")
set_tests_properties(HyperedgeTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(HypergraphTest "/home/mohamednadeem/project/htd/test/htd/HypergraphTest")
set_tests_properties(HypergraphTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(HypertreeDecompositionAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/HypertreeDecompositionAlgorithmTest")
set_tests_properties(HypertreeDecompositionAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(HypertreeDecompositionTest "/home/mohamednadeem/project/htd/test/htd/HypertreeDecompositionTest")
set_tests_properties(HypertreeDecompositionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(IteratorTest "/home/mohamednadeem/project/htd/test/htd/IteratorTest")
set_tests_properties(IteratorTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(LabelCollectionTest "/home/mohamednadeem/project/htd/test/htd/LabelCollectionTest")
set_tests_properties(LabelCollectionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(LabeledDirectedGraphTest "/home/mohamednadeem/project/htd/test/htd/LabeledDirectedGraphTest")
set_tests_properties(LabeledDirectedGraphTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(LabeledDirectedMultiGraphTest "/home/mohamednadeem/project/htd/test/htd/LabeledDirectedMultiGraphTest")
set_tests_properties(LabeledDirectedMultiGraphTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(LabeledGraphTest "/home/mohamednadeem/project/htd/test/htd/LabeledGraphTest")
set_tests_properties(LabeledGraphTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(LabeledHypergraphTest "/home/mohamednadeem/project/htd/test/htd/LabeledHypergraphTest")
set_tests_properties(LabeledHypergraphTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(LabeledMultiGraphTest "/home/mohamednadeem/project/htd/test/htd/LabeledMultiGraphTest")
set_tests_properties(LabeledMultiGraphTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(LabelingCollectionTest "/home/mohamednadeem/project/htd/test/htd/LabelingCollectionTest")
set_tests_properties(LabelingCollectionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(LibraryInstanceTest "/home/mohamednadeem/project/htd/test/htd/LibraryInstanceTest")
set_tests_properties(LibraryInstanceTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(ManipulationOperationTest "/home/mohamednadeem/project/htd/test/htd/ManipulationOperationTest")
set_tests_properties(ManipulationOperationTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(MaximumCardinalitySearchOrderingAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/MaximumCardinalitySearchOrderingAlgorithmTest")
set_tests_properties(MaximumCardinalitySearchOrderingAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(MinDegreeOrderingAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/MinDegreeOrderingAlgorithmTest")
set_tests_properties(MinDegreeOrderingAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(MinFillOrderingAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/MinFillOrderingAlgorithmTest")
set_tests_properties(MinFillOrderingAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(MultiGraphTest "/home/mohamednadeem/project/htd/test/htd/MultiGraphTest")
set_tests_properties(MultiGraphTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(MultiHypergraphTest "/home/mohamednadeem/project/htd/test/htd/MultiHypergraphTest")
set_tests_properties(MultiHypergraphTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(PathDecompositionTest "/home/mohamednadeem/project/htd/test/htd/PathDecompositionTest")
set_tests_properties(PathDecompositionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(PathTest "/home/mohamednadeem/project/htd/test/htd/PathTest")
set_tests_properties(PathTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(PostProcessingPathDecompositionAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/PostProcessingPathDecompositionAlgorithmTest")
set_tests_properties(PostProcessingPathDecompositionAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(RandomOrderingAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/RandomOrderingAlgorithmTest")
set_tests_properties(RandomOrderingAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(SetCoverAlgorithmTest "/home/mohamednadeem/project/htd/test/htd/SetCoverAlgorithmTest")
set_tests_properties(SetCoverAlgorithmTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(TreeDecompositionOptimizationTest "/home/mohamednadeem/project/htd/test/htd/TreeDecompositionOptimizationTest")
set_tests_properties(TreeDecompositionOptimizationTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(TreeDecompositionTest "/home/mohamednadeem/project/htd/test/htd/TreeDecompositionTest")
set_tests_properties(TreeDecompositionTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(TreeTest "/home/mohamednadeem/project/htd/test/htd/TreeTest")
set_tests_properties(TreeTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
add_test(VertexSelectionStrategyTest "/home/mohamednadeem/project/htd/test/htd/VertexSelectionStrategyTest")
set_tests_properties(VertexSelectionStrategyTest PROPERTIES  _BACKTRACE_TRIPLES "/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;33;add_test;/home/mohamednadeem/project/htd/test/htd/CMakeLists.txt;0;")
